# Importing the libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# converting dataset to dataframe

In [2]:
data = pd.read_csv("data.csv")

In [3]:
data

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [4]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

# Splitting data train and test set

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [6]:
x_train.shape

(7654, 4)

In [7]:
y_train.shape

(7654,)

In [8]:
y_train= y_train.reshape(len(y_train),1)
y_train

array([[473.93],
       [467.87],
       [431.97],
       ...,
       [459.01],
       [462.72],
       [428.12]])

# Feature scaling

In [9]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
scaler_y = StandardScaler()
x_train_svr = scaler_x.fit_transform(x_train)
y_train_svr = scaler_y.fit_transform(y_train)
x_train, y_train

(array([[  11.22,   43.13, 1017.24,   80.9 ],
        [  13.67,   54.3 , 1015.92,   75.42],
        [  32.84,   77.95, 1014.68,   45.8 ],
        ...,
        [  16.81,   38.52, 1018.26,   75.21],
        [  12.8 ,   41.16, 1022.43,   86.19],
        [  32.32,   67.9 , 1006.08,   37.93]]),
 array([[473.93],
        [467.87],
        [431.97],
        ...,
        [459.01],
        [462.72],
        [428.12]]))

# Multiple Linear regression

In [10]:
from sklearn.linear_model import LinearRegression
LR_alg = LinearRegression()
LR_alg.fit(x_train, y_train)

LinearRegression()

# Polynomial Regression

In [11]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
x_poly = poly_reg.fit_transform(x_train)
LR_polynomial = LinearRegression()
LR_polynomial.fit(x_poly, y_train)

LinearRegression()

# SVR

In [12]:
from sklearn.svm import SVR
alg_SVR = SVR(kernel = 'rbf')
alg_SVR.fit(x_train_svr, y_train_svr.ravel())

SVR()

# Decision Tree

In [13]:
from sklearn.tree import DecisionTreeRegressor
alg_DTree = DecisionTreeRegressor()
alg_DTree.fit(x_train, y_train)

DecisionTreeRegressor()

# Random Forrest classifier

In [14]:
from sklearn.ensemble import RandomForestRegressor
alg_RFR = RandomForestRegressor(n_estimators=100)
alg_RFR.fit(x_train, y_train.ravel())

RandomForestRegressor()

# Predicting the test result

In [15]:
from sklearn.metrics import r2_score

In [16]:
x_test.shape

(1914, 4)

### Multiple Linear Regression

In [17]:
y_pred_LR = LR_alg.predict(x_test)
r2_score(y_test, y_pred_LR)

0.9325315554761302

### Polynomial Regression

In [18]:
y_pred_poly_LR = LR_polynomial.predict(poly_reg.transform(x_test))
r2_score(y_test, y_pred_poly_LR)

0.9458193001159928

### SVR

In [19]:
y_pred_SVR = scaler_y.inverse_transform(alg_SVR.predict(scaler_x.transform(x_test)))
r2_score(y_test, y_pred_SVR)

0.9480784049986258

### Decision Tree

In [20]:
y_pred_DT = alg_DTree.predict(x_test)
r2_score(y_test, y_pred_SVR)

0.9480784049986258

### random Forrest classifier

In [21]:
y_pred_RF = alg_RFR.predict(x_test)
r2_score(y_test, y_pred_RF)

0.9649902744118705